name: Lint

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2.3.0
        with:
          python-version: 3.9
      - name: Install project dependencies
        run: |
          pip install tensorflow-cpu==2.7.0
          pip install -e .[test]
      - name: Run Flake8
        run: flake8
      - name: Black code style
        run: black --check --target-version py36 .
      - name: Docstring formatting
        run: docformatter -c -r . --wrap-summaries 88 --wrap-descriptions 88
      - name: Check import order with isort
        run: isort . --check --diff
      - name: Type check with PyType
        run: pytype --jobs 2
