name: Lint

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install project dependencies
        run: |
          pip install tensorflow==2.0.0 colorama==0.4.1
          pip install -e .[test]
      - name: Install Lint Dependencies
        run: pip install flake8==3.7.9 black==19.10b0 pytype==2019.10.17 isort==4.3.21
      - name: Run flake8
        run: flake8 --ignore=E203,E501,W503 --exclude build,dist
      - name: Black code style
        run: black . --check --target-version py37 --exclude 'build/|buck-out/|dzzist/|_build/|\.git/|\.hg/|\.mypy_cache/|\.tox/|\.venv/|larq/snapshots/'
      - name: Check import order with isort
        run: isort --check-only --diff --use-parentheses --trailing-comma -m 3 -l 88 -o larq -rc zookeeper examples setup.py
      - name: Type check with PyType
        run: pytype -V 3.7 --keep-going --exclude build dist .pytype examples -- .
