name: Lint

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2.1.4
        with:
          python-version: 3.7
      - name: Install project dependencies
        run: |
          pip install tensorflow==2.2.0 colorama==0.4.1
          pip install -e .[test]
      - name: Run Flake8
        run: flake8
      - name: Black code style
        run: black --check --target-version py36 .
      - name: Check import order with isort
        run: isort . --check --diff
      - name: Type check with PyType
        run: pytype --jobs 2
